# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('azuredevops-extensions')


class _ExportableConfig(types.ModuleType):
    @property
    def number_of_attempts(self) -> Optional[int]:
        """
        The number of attempts.
        """
        return __config__.get_int('numberOfAttempts') or _utilities.get_env_int('NUMBER_OF_ATTEMPTS')

    @property
    def org_service_url(self) -> Optional[str]:
        """
        The url of the Azure DevOps instance which should be used.
        """
        return __config__.get('orgServiceUrl') or _utilities.get_env('AZDO_ORG_SERVICE_URL')

    @property
    def personal_access_token(self) -> Optional[str]:
        """
        The personal access token which should be used.
        """
        return __config__.get('personalAccessToken') or _utilities.get_env('AZDO_PERSONAL_ACCESS_TOKEN')

