// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const RoleName = {
    Reader: "Reader",
    Administrator: "Administrator",
    User: "User",
} as const;

export type RoleName = (typeof RoleName)[keyof typeof RoleName];

export const ScopeName = {
    VariableGroup: "VariableGroup",
    ServiceEndpoint: "ServiceEndpoint",
    Environment: "Environment",
} as const;

export type ScopeName = (typeof ScopeName)[keyof typeof ScopeName];
