// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureDevopsExtensions.Outputs
{

    [OutputType]
    public sealed class KubernetesResource
    {
        /// <summary>
        /// The resource cluster name.
        /// </summary>
        public readonly string ClusterName;
        /// <summary>
        /// The resource name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The resource namemespace.
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// The service endpoint id.
        /// </summary>
        public readonly string ServiceEndpointId;

        [OutputConstructor]
        private KubernetesResource(
            string clusterName,

            string name,

            string @namespace,

            string serviceEndpointId)
        {
            ClusterName = clusterName;
            Name = name;
            Namespace = @namespace;
            ServiceEndpointId = serviceEndpointId;
        }
    }
}
