# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .build_folder import *
from .pipeline_environment import *
from .provider import *
from .role_assignment import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_azuredevops_extensions.config as config
else:
    config = _utilities.lazy_import('pulumi_azuredevops_extensions.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "azuredevops-extensions",
  "mod": "index",
  "fqn": "pulumi_azuredevops_extensions",
  "classes": {
   "azuredevops-extensions:index:BuildFolder": "BuildFolder",
   "azuredevops-extensions:index:PipelineEnvironment": "PipelineEnvironment",
   "azuredevops-extensions:index:RoleAssignment": "RoleAssignment"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "azuredevops-extensions",
  "token": "pulumi:providers:azuredevops-extensions",
  "fqn": "pulumi_azuredevops_extensions",
  "class": "Provider"
 }
]
"""
)
