# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['PipelineEnvironmentArgs', 'PipelineEnvironment']

@pulumi.input_type
class PipelineEnvironmentArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[str],
                 project_id: pulumi.Input[str],
                 kubernetes_resources: Optional[pulumi.Input[Sequence[pulumi.Input['KubernetesResourceArgs']]]] = None):
        """
        The set of arguments for constructing a PipelineEnvironment resource.
        :param pulumi.Input[str] project_id: The project ID or project name.
        :param pulumi.Input[Sequence[pulumi.Input['KubernetesResourceArgs']]] kubernetes_resources: List of kubernetes resources.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "project_id", project_id)
        if kubernetes_resources is not None:
            pulumi.set(__self__, "kubernetes_resources", kubernetes_resources)

    @property
    @pulumi.getter
    def name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[str]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[str]:
        """
        The project ID or project name.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "project_id", value)

    @property
    @pulumi.getter(name="kubernetesResources")
    def kubernetes_resources(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['KubernetesResourceArgs']]]]:
        """
        List of kubernetes resources.
        """
        return pulumi.get(self, "kubernetes_resources")

    @kubernetes_resources.setter
    def kubernetes_resources(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['KubernetesResourceArgs']]]]):
        pulumi.set(self, "kubernetes_resources", value)


class PipelineEnvironment(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 kubernetes_resources: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['KubernetesResourceArgs']]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 project_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a PipelineEnvironment resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['KubernetesResourceArgs']]]] kubernetes_resources: List of kubernetes resources.
        :param pulumi.Input[str] project_id: The project ID or project name.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PipelineEnvironmentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a PipelineEnvironment resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PipelineEnvironmentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PipelineEnvironmentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 kubernetes_resources: Optional[pulumi.Input[Sequence[pulumi.Input[pulumi.InputType['KubernetesResourceArgs']]]]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 project_id: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PipelineEnvironmentArgs.__new__(PipelineEnvironmentArgs)

            __props__.__dict__["kubernetes_resources"] = kubernetes_resources
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
        super(PipelineEnvironment, __self__).__init__(
            'azuredevops-extensions:index:PipelineEnvironment',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'PipelineEnvironment':
        """
        Get an existing PipelineEnvironment resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = PipelineEnvironmentArgs.__new__(PipelineEnvironmentArgs)

        __props__.__dict__["kubernetes_resources"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["project_id"] = None
        return PipelineEnvironment(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="kubernetesResources")
    def kubernetes_resources(self) -> pulumi.Output[Optional[Sequence['outputs.KubernetesResource']]]:
        """
        List of kubernetes resources.
        """
        return pulumi.get(self, "kubernetes_resources")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The environment name.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[str]:
        """
        The project ID or project name.
        """
        return pulumi.get(self, "project_id")

