// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface KubernetesResource {
    /**
     * The resource cluster name.
     */
    clusterName: string;
    /**
     * The resource name.
     */
    name: string;
    /**
     * The resource namemespace.
     */
    namespace: string;
    /**
     * The service endpoint id.
     */
    serviceEndpointId: string;
}

