// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./pipelineEnvironment";
export * from "./provider";
export * from "./roleAssignment";

// Export enums:
export * from "./types/enums";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

// Import resources to register:
import { PipelineEnvironment } from "./pipelineEnvironment";
import { RoleAssignment } from "./roleAssignment";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "azuredevops-extensions:index:PipelineEnvironment":
                return new PipelineEnvironment(name, <any>undefined, { urn })
            case "azuredevops-extensions:index:RoleAssignment":
                return new RoleAssignment(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("azuredevops-extensions", "index", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("azuredevops-extensions", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:azuredevops-extensions") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
